# Generated by Django 3.0 on 2019-12-09 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='bairro',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='cidade',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='logradouro',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='escolaridade',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Ensino Fundamental'), (2, 'Ensino Fundamental incompleto'), (3, 'Ensino Médio'), (4, 'Ensino Médio incompleto'), (5, 'Ensino Superior'), (6, 'Ensino Superior incompleto')]),
        ),
        migrations.CreateModel(
            name='Pertence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField()),
                ('funcao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grupos.Funcao')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grupos.Grupo')),
            ],
        ),
    ]
